---
title: "NY_NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, include = FALSE}
data("ny_noaa")

ny_noaa = 
  ny_noaa %>% 
  as_tibble(ny_noaa) %>% 
  drop_na() %>% 
  sample_n(1000) %>% 
  separate(date, c('year', 'month', 'day'), convert = TRUE, remove = FALSE) %>% 
  mutate(
    month = month.name[month], 
    month = factor(month, levels = month.name),
    tmax = as.numeric(tmax) / 10,
    tmin = as.numeric(tmin) / 10,
    prcp = prcp / 10)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Box plot

```{r}
ny_noaa %>% 
  group_by(month) %>%
  plot_ly(
    y = ~tmax, 
    color = ~month,
    type = "box", 
    colors = "viridis") %>% 
  layout(title = "Daily Maximum temperature(째C) by month",
         xaxis = list (title = "Month", 
                       zeroline = FALSE),
         yaxis = list (title = "Daily Maximum temperature(째C)",
                       zeroline = FALSE))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Scatter plot

```{r}
ny_noaa %>% 
  mutate(
    text_label = str_c("Date: ", date)
  ) %>% 
  plot_ly(
    x = ~tmax, 
    y = ~tmin,
    type = 'scatter',
    mode = "markers",
    alpha = .5,
    text = ~text_label
    ) %>% 
  layout(title = "Maximum vs Minimum Daily temperature",
         xaxis = list (title = "Daily Maximum temperature(째C)", 
                       zeroline = FALSE),
         yaxis = list (title = "Daily Minimum temperature(째C)",
                       zeroline = FALSE))
```

### Bar plot
```{r}
ny_noaa %>% 
  group_by(year) %>% 
  summarise(
    n_date = n()
  ) %>% 
  plot_ly(
    x = ~year, 
    y = ~n_date,
    type = 'bar'
    ) %>% 
  layout(title = "Number of days recorded for each year",
         yaxis = list (title = "Number of days"))
```

